set(CMAKE_SYSTEM_PROCESSOR aarch64)
#set(GCC_COMPILER_VERSION "" CACHE STRING "GCC Compiler version")
set(GNU_MACHINE "aarch64-linux-gnu" CACHE STRING "GNU compiler triple")
set(CMAKE_SYSTEM_NAME Linux)
#set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_COMPILER /usr/bin/${GNU_MACHINE}-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/${GNU_MACHINE}-g++)
find_program(CMAKE_LINKER NAMES ${GNU_MACHINE}-ld ${GNU_MACHINE}-ld)
find_program(CMAKE_AR NAMES ${GNU_MACHINE}-ar ${GNU_MACHINE}-ar)
#set(ARM_LINUX_SYSROOT /usr/${GNU_MACHINE})


#if(NOT DEFINED CMAKE_CXX_FLAGS)
#  set(CMAKE_CXX_FLAGS           "" CACHE INTERNAL "")
#  set(CMAKE_C_FLAGS             "" CACHE INTERNAL "")
#  set(CMAKE_SHARED_LINKER_FLAGS "" CACHE INTERNAL "")
#  set(CMAKE_MODULE_LINKER_FLAGS "" CACHE INTERNAL "")
#  set(CMAKE_EXE_LINKER_FLAGS    "" CACHE INTERNAL "")
#  set(CMAKE_CXX_FLAGS           "${CMAKE_CXX_FLAGS} -fdata-sections -Wa,--noexecstack -fsigned-char -Wno-psabi")
#  set(CMAKE_C_FLAGS             "${CMAKE_C_FLAGS} -fdata-sections -Wa,--noexecstack -fsigned-char -Wno-psabi")
#  if(CMAKE_SYSTEM_PROCESSOR STREQUAL aarch64)
#    set(ARM_LINKER_FLAGS "-Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now")
#  endif()
#  set(CMAKE_SHARED_LINKER_FLAGS "${ARM_LINKER_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS}")
#  set(CMAKE_MODULE_LINKER_FLAGS "${ARM_LINKER_FLAGS} ${CMAKE_MODULE_LINKER_FLAGS}")
#  set(CMAKE_EXE_LINKER_FLAGS    "${ARM_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS}")
#endif()


